import { Tech, TechDetailed } from '../models';

export const techStack: TechDetailed[] = [
  {
    name: Tech.HTML,
    docsUrl: 'https://developer.mozilla.org/en-US/docs/Web/HTML',
    iconSrc: 'assets/icons/html.png',
    category: 'Frontend',
    description: 'Standard markup language for web pages.',
  },
  {
    name: Tech.CSS,
    docsUrl: 'https://developer.mozilla.org/en-US/docs/Web/CSS',
    iconSrc: 'assets/icons/css.svg',
    category: 'Frontend',
    description: 'Style sheet language for web design.',
  },
  {
    name: Tech.JavaScript,
    docsUrl: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript',
    iconSrc: 'assets/icons/javascript.png',
    category: 'Frontend',
    description: 'Scripting language for web development.',
  },
  {
    name: Tech.SCSS,
    docsUrl: 'https://sass-lang.com/documentation',
    iconSrc: 'assets/icons/scss.ico',
    category: 'Frontend',
    description: 'Sass CSS preprocessor syntax.',
  },
  {
    name: Tech.TypeScript,
    docsUrl: 'https://www.typescriptlang.org/docs/',
    iconSrc: 'assets/icons/typescript.ico',
    category: 'Frontend',
    description: 'Typed superset of JavaScript.',
  },
  {
    name: Tech.React,
    docsUrl: 'https://reactjs.org/docs/getting-started.html',
    iconSrc: 'assets/icons/react.ico',
    category: 'Frontend',
    description: 'JavaScript library for building UIs.',
  },
  {
    name: Tech.Angular,
    docsUrl: 'https://angular.dev/overview',
    iconSrc: 'assets/icons/angular.ico',
    category: 'Frontend',
    description: 'Platform for building mobile and desktop web applications.',
  },
  {
    name: Tech.AngularMaterial,
    docsUrl: 'https://material.angular.io/',
    iconSrc: 'assets/icons/angular-material.png',
    category: 'Frontend',
    description: 'UI component library for Angular.',
  },
  {
    name: Tech.AngularCDK,
    docsUrl: 'https://material.angular.io/cdk/categories',
    iconSrc: 'assets/icons/angular-material.png',
    category: 'Frontend',
    description: 'Component Dev Kit for Angular.',
  },
  {
    name: Tech.RxJS,
    docsUrl: 'https://rxjs.dev/guide/overview',
    iconSrc: 'assets/icons/rxjs.ico',
    category: 'Frontend',
    description: 'Reactive programming library for JavaScript.',
  },
  {
    name: Tech.JQuery,
    docsUrl: 'https://jquery.com/',
    iconSrc: 'assets/icons/jquery.ico',
    category: 'Frontend',
    description: 'Fast, small, and feature-rich JavaScript library.',
  },
  {
    name: Tech.Lit,
    docsUrl: 'https://lit.dev/docs/',
    iconSrc: 'assets/icons/lit.svg',
    category: 'Frontend',
    description: 'Library for building fast web components.',
  },
  {
    name: Tech.NodeJS,
    docsUrl: 'https://nodejs.org/docs/latest/api/documentation.html',
    iconSrc: 'assets/icons/nodejs.png',
    category: 'Backend',
    description: 'JavaScript runtime built on V8 engine.',
  },
  {
    name: Tech.FeathersJS,
    docsUrl: 'https://feathersjs.com/',
    iconSrc: 'assets/icons/feathersjs.ico',
    category: 'Backend',
    description: 'A framework for real-time applications.',
  },
  {
    name: Tech.REST,
    docsUrl: 'https://restfulapi.net/',
    iconSrc: 'assets/icons/rest.ico',
    category: 'API',
    description: 'Architectural style for web services.',
  },
  {
    name: Tech.GraphQL,
    docsUrl: 'https://graphql.org/learn/',
    iconSrc: 'assets/icons/graphql.ico',
    category: 'API',
    description: 'Query language for APIs.',
  },
  {
    name: Tech.Jest,
    docsUrl: 'https://jestjs.io/docs/getting-started',
    iconSrc: 'assets/icons/jest.png',
    category: 'Testing',
    description: 'JavaScript testing framework.',
  },
  {
    name: Tech.Docker,
    docsUrl: 'https://docs.docker.com/',
    iconSrc: 'assets/icons/docker.ico',
    category: 'DevOps',
    description: 'Platform for containerizing applications.',
  },
  {
    name: Tech.GitHub,
    docsUrl: 'https://docs.github.com/en/get-started/start-your-journey/about-github-and-git',
    iconSrc: 'assets/icons/github.png',
    category: 'Version Control',
    description: 'Code hosting platform for version control.',
  },
  {
    name: Tech.Nx,
    docsUrl: 'https://nx.dev/',
    iconSrc: 'assets/icons/nx.ico',
    category: 'Tools',
    description: 'Smart extensible build framework.',
  },
  {
    name: Tech.Webpack,
    docsUrl: 'https://webpack.js.org/concepts/',
    iconSrc: 'assets/icons/webpack.svg',
    category: 'Tools',
    description: 'Module bundler for JavaScript.',
  },
  {
    name: Tech.Vite,
    docsUrl: 'https://vitejs.dev/guide/',
    iconSrc: 'assets/icons/vite.ico',
    category: 'Tools',
    description: 'Next-generation frontend tooling.',
  },
  {
    name: Tech.Rollup,
    docsUrl: 'https://rollupjs.org/guide/en/',
    iconSrc: 'assets/icons/rollup.ico',
    category: 'Tools',
    description: 'JavaScript module bundler.',
  },
  {
    name: Tech.Lodash,
    docsUrl: 'https://lodash.com/docs/4.17.15',
    iconSrc: 'assets/icons/lodash.ico',
    category: 'Frontend',
    description: 'Utility library for JavaScript.',
  },
  {
    name: Tech.RamdaJS,
    docsUrl: 'https://ramdajs.com/',
    iconSrc: 'assets/icons/ramda.ico',
    category: 'Frontend',
    description: 'Functional programming library for JavaScript.',
  },
  {
    name: Tech.TailwindCSS,
    docsUrl: 'https://tailwindcss.com/docs',
    iconSrc: 'assets/icons/tailwindcss.ico',
    category: 'Frontend',
    description: 'Utility-first CSS framework.',
  },
  {
    name: Tech.Scullyio,
    docsUrl: 'https://scully.io/docs/',
    iconSrc: 'assets/icons/scullyio.ico',
    category: 'Frontend',
    description: 'Static site generator for Angular projects.',
  },
  {
    name: Tech.NPM,
    docsUrl: 'https://docs.npmjs.com/',
    iconSrc: 'assets/icons/npm.ico',
    category: 'Tools',
    description: 'Package manager for JavaScript.',
  },
  {
    name: Tech.Jenkins,
    docsUrl: 'https://www.jenkins.io/doc/',
    iconSrc: 'assets/icons/jenkins.ico',
    category: 'CI/CD',
    description: 'Automation server for building, deploying.',
  },
  {
    name: Tech.Swagger,
    docsUrl: 'https://swagger.io/docs/',
    iconSrc: 'assets/icons/swagger.png',
    category: 'API',
    description: 'API design and documentation tool.',
  },
  {
    name: Tech.Mocha,
    docsUrl: 'https://mochajs.org/',
    iconSrc: 'assets/icons/mocha.ico',
    category: 'Testing',
    description: 'JavaScript test framework for Node.js.',
  },
  {
    name: Tech.Chai,
    docsUrl: 'https://www.chaijs.com/',
    iconSrc: 'assets/icons/chai.ico',
    category: 'Testing',
    description: 'Assertion library for browsers and Node.js.',
  },
  {
    name: Tech.GitLab,
    docsUrl: 'https://docs.gitlab.com/',
    iconSrc: 'assets/icons/gitlab.png',
    category: 'Version Control',
    description: 'Git repository manager.',
  },
  {
    name: Tech.Storybook,
    docsUrl: 'https://storybook.js.org/',
    iconSrc: 'assets/icons/storybook.svg',
    category: 'Frontend',
    description: 'UI component explorer for React, Vue, Angular.',
  },
  {
    name: Tech.ElectronJS,
    docsUrl: 'https://www.electronjs.org/docs',
    iconSrc: 'assets/icons/electronjs.ico',
    category: 'Frontend',
    description: 'Build cross-platform desktop apps with JavaScript.',
  },
  {
    name: Tech.Podman,
    docsUrl: 'https://podman.io/getting-started/',
    iconSrc: 'assets/icons/podman.ico',
    category: 'DevOps',
    description: 'Tool for managing OCI containers.',
  },
  {
    name: Tech.GitOps,
    docsUrl: 'https://www.gitops.tech/',
    iconSrc: 'assets/icons/gitops.ico',
    category: 'DevOps',
    description: 'Operating model for cloud-native applications.',
  },
  {
    name: Tech.Karma,
    docsUrl: 'https://karma-runner.github.io/latest/index.html',
    iconSrc: 'assets/icons/karma.ico',
    category: 'Testing',
    description: 'Test runner for JavaScript.',
  },
  {
    name: Tech.Cypress,
    docsUrl: 'https://docs.cypress.io/',
    iconSrc: 'assets/icons/cypress.ico',
    category: 'Testing',
    description: 'End-to-end testing framework.',
  },
  {
    name: Tech.MariaDB,
    docsUrl: 'https://mariadb.com/kb/en/documentation/',
    iconSrc: 'assets/icons/mariadb.ico',
    category: 'Database',
    description: 'Relational database management system.',
  },
  {
    name: Tech.Firebase,
    docsUrl: 'https://firebase.google.com/docs',
    iconSrc: 'assets/icons/firebase.ico',
    category: 'Backend',
    description: 'Platform for app development.',
  },
  {
    name: Tech.WebSockets,
    docsUrl: 'https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API',
    iconSrc: 'assets/icons/socketio.png',
    category: 'Networking',
    description: 'Protocol for full-duplex communication channels.',
  },
  {
    name: Tech.VirtualBox,
    docsUrl: 'https://www.virtualbox.org/wiki/Documentation',
    iconSrc: 'assets/icons/virtualbox.ico',
    category: 'Virtualization',
    description: 'Open-source hosted hypervisor.',
  },
  {
    name: Tech.ATCommands,
    docsUrl: 'https://en.wikipedia.org/wiki/Hayes_command_set',
    iconSrc: 'assets/icons/gsm.svg',
    category: 'Communications',
    description: 'Instruction set for modems.',
  },
  {
    name: Tech.SerialPort,
    docsUrl: 'https://serialport.io/docs/',
    iconSrc: 'assets/icons/serialport.ico',
    category: 'Hardware',
    description: 'Node.js library for serial port communication.',
  },
  {
    name: Tech.SolidJS,
    docsUrl: 'https://solidjs.com/docs',
    iconSrc: 'assets/icons/solidjs.ico',
    category: 'Frontend',
    description: 'Reactive UI library.',
  },
  {
    name: Tech.Mockoon,
    docsUrl: 'https://mockoon.com/docs/',
    iconSrc: 'assets/icons/mockoon.ico',
    category: 'Testing',
    description: 'API mock tool for local testing.',
  },
  {
    name: Tech.Playwright,
    docsUrl: 'https://playwright.dev/docs/intro',
    iconSrc: 'assets/icons/playwright.ico',
    category: 'Testing',
    description: 'Automated testing for web applications.',
  },
  {
    name: Tech.DebianLinux,
    docsUrl: 'https://www.debian.org/doc/',
    iconSrc: 'assets/icons/debian.ico',
    category: 'Operating System',
    description: 'Popular open-source Linux distribution.',
  },
  {
    name: Tech.Git,
    docsUrl: 'https://git-scm.com/doc',
    iconSrc: 'assets/icons/git.ico',
    category: 'Version Control',
    description: 'Distributed version control system.',
  },
  {
    name: Tech.Jira,
    docsUrl: 'https://www.atlassian.com/software/jira/guides',
    iconSrc: 'assets/icons/jira.png',
    category: 'Project Management',
    description: 'Tool for bug tracking and project management.',
  },
  {
    name: Tech.Jasmine,
    docsUrl: 'https://jasmine.github.io/pages/docs_home.html',
    iconSrc: 'assets/icons/jasmine.ico',
    category: 'Testing',
    description:
      'Behavior-driven development framework for testing JavaScript.',
  },
  {
    name: Tech.Spectator,
    docsUrl: 'https://ngneat.github.io/spectator/',
    iconSrc: 'assets/icons/spectator.ico',
    category: 'Testing',
    description: 'Angular testing library.',
  },
  {
    name: Tech.Bitbucket,
    docsUrl: 'https://bitbucket.org/product/version-control-software',
    iconSrc: 'assets/icons/bitbucket.png',
    category: 'Version Control',
    description: 'Git repository management solution.',
  },
  {
    name: Tech.BootstrapCSS,
    docsUrl: 'https://getbootstrap.com/docs/',
    iconSrc: 'assets/icons/bootstrapcss.png',
    category: 'Frontend',
    description: 'Popular CSS framework for responsive design.',
  },
  {
    name: Tech.FoundationCSS,
    docsUrl: 'https://get.foundation/sites/docs/',
    iconSrc: 'assets/icons/foundation.png',
    category: 'Frontend',
    description: 'Responsive front-end framework.',
  },
  {
    name: Tech.WebComponents,
    docsUrl: 'https://www.webcomponents.org/introduction',
    iconSrc: 'assets/icons/webcomponents.svg',
    category: 'Frontend',
    description: 'Technology suite for reusable components.',
  },
  {
    name: Tech.SCRUM,
    docsUrl: 'https://www.scrum.org/resources/what-is-scrum',
    iconSrc: 'assets/icons/scrum.ico',
    category: 'Project Management',
    description: 'Agile framework for managing projects.',
  },
  {
    name: Tech.Kanban,
    docsUrl: 'https://www.atlassian.com/agile/kanban',
    iconSrc: 'assets/icons/noun-kanban-4193457.svg',
    category: 'Project Management',
    description: 'Visual workflow management method.',
  }

  // Add similar entries for each tech in Tech...
];

// Ensure to fill in similar pattern for all other entries in Tech.
